###
POST http://localhost:3000/skud/access
Content-Type: application/json

{
    "data":"123123"
}

###
POST http://localhost:3000/skud/key
Content-Type: application/json

{
    "data":"396387",
    "owner":"Климат Проф Антон"
}

###
PUT http://localhost:3000/skud/key
Content-Type: application/json

{
    "data": "35B188",
    "owner":"Казакова Светлана Евгеньевна"
}

###
GET http://localhost:3000/skud/keys
Content-Type: application/json

###
GET http://localhost:3000/skud/keysfull
Content-Type: application/json

###
POST http://localhost:3000/skud/access
Content-Type: application/json

{
    "data":"35B188"
}


###
GET http://localhost:3000/skud/access
Content-Type: application/json