###
POST http://localhost:3000/skud/access
Content-Type: application/json

{
    "data":"123123"
}

###
POST http://localhost:3000/skud/key
Content-Type: application/json

{
    "data":"887B06",
    "owner":"Казаков Геворк Аркадьевич"
}

###
PUT http://localhost:3000/skud/key
Content-Type: application/json

{
    "data": "2741F9",
    "owner":"Алексеев Владимир Львович"
}

###
GET http://localhost:3000/skud/keys
Content-Type: application/json

###
GET http://localhost:3000/skud/keysfull
Content-Type: application/json

###
POST http://localhost:3000/skud/access
Content-Type: application/json

{
    "data":"35B188"
}


###
GET http://localhost:3000/skud/access
Content-Type: application/json

###
PATCH http://localhost:3000/skud/access
Content-Type: application/json